export const USERS = [
  {
    id: "user-admin",
    username: "admin",
    password: "CTPSTEM123",
    name: "Admin",
    role: "ADMIN",
    avatar: "AD",
    skills: ["Management", "STEM"],
    bio: "Administrator of CTP Scientia.",
    department: "Ban Chủ Nhiệm",
  },
  {
    id: "user-member1",
    username: "member1",
    password: "pass123",
    name: "Nguyễn Văn A",
    role: "MEMBER",
    avatar: "NA",
    skills: ["Robot", "IoT"],
    bio: "Passionate about robotics and automation.",
    department: "Ban Kỹ Thuật",
  },
  {
    id: "user-member2",
    username: "member2",
    password: "pass123",
    name: "Trần Thị B",
    role: "MEMBER",
    avatar: "TB",
    skills: ["Design", "3D Printing"],
    bio: "Creative designer and 3D modeling enthusiast.",
    department: "Ban Truyền Thông",
  },
  {
    id: "user-member3",
    username: "Shio",
    password: "Cuong4711@",
    name: "Dương Đức Cương",
    role: "ADMIN",
    avatar: "DC",
    skills: ["Robot", "In 3D", "IoT", "CNC", "Thiết kế", "Arduino", "Lập trình"],
    bio: "",
    department: "Ban Kỹ Thuật",
  },
];
